### ISSUE TITLE
*.cl files don't react on header file changes

### ISSUE THREAD

**Issue by shampletov-no** [Galarius/vscode-opencl#44]
I've been working on my project in VS code 1.72.2 and recently noticed that `#include "params.h"` goes wrong. I've added some new `#define`s in the header but *.cl file gave me `use of undeclared identifier` error. It seems like a cach of the old params.h is preserved somewhere and doesn't update.

Then I've created new empty folder to test that problem, fill it with only one file, `test.cl`, and tried to include old header `params.h`. And no errors occure despite no `params.h` is located in test folder. Also I can use old definitions of `params.h`, but not the new ones. I really think the cach is somewhere in my PC but I can't find it. Can you help?

Screen of test folder structure:
![image](https://user-images.githubusercontent.com/36101680/197567195-222c7b32-4bf0-421c-af03-6e864e8d8a93.png)

I've tried to reinstall the extension, reinstall VS Code (with cleaning %APPDATA%\Code and %USERPROFILE%\ .vscode). It doesn't help.

**Comment by Galarius** [comment]
Hello, @shampletov-no. Could you share the spec of your OpenCL device? If the provider is Nvidia, there is an environment variable called `CUDA_CACHE_DISABLE` (claimed to work for OpenCL as well). In addition, the cache is stored in the `%AppData%\NVIDIA\ComputeCache` directory.

Reference: https://forums.developer.nvidia.com/t/disable-caching-by-the-opencl-compiler/23752/3

**Comment by shampletov-no** [comment]
Hello, @Galarius. I'm using AMD GPU (AMD Radeon 530 Series). Also I've checked my environment variables and haven't found any `...CACHE_DISABLE` or similar, it seems AMD doesn't have such a variable.

I forget to mention that I'm working on Windows. Maybe it's crucial.

**Comment by shampletov-no** [comment]
### Interesting solution

Solving another problem I found that after **disabling** and subsequent **enabling** of the underlined extensions the problem is gone... Strange, but it works for me.

![image](https://user-images.githubusercontent.com/36101680/197797339-13d411db-568c-4488-8d51-5870089b4627.png)

Thank you, and sorry for the interruption)

**Comment by Galarius** [comment]
Feel free to re-open the ticket if the issue persists.
